[windows]
vm-devops ansible_host=4.154.64.129

[windows:vars]
ansible_user=azureuser
ansible_password=P@ssword1234!
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_port=5986