name: Build Image and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'packer/**'
      - 'scripts/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # -----------------------
    # Checkout Repository
    # -----------------------
    - name: Checkout
      uses: actions/checkout@v4

    # -----------------------
    # Azure Login
    # -----------------------
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # -----------------------
    # Setup Packer
    # -----------------------
    - name: Setup Packer
      uses: hashicorp/setup-packer@v2

    # -----------------------
    # Packer Init
    # -----------------------
    - name: Packer Init
      run: packer init ./packer

    # -----------------------
    # Debug ARM Variables
    # -----------------------
    - name: Debug ARM Variables
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: |
        if [ -z "$ARM_CLIENT_ID" ]; then
          echo "ARM_CLIENT_ID missing"
        else
          echo "ARM_CLIENT_ID exists"
        fi

        if [ -z "$ARM_CLIENT_SECRET" ]; then
          echo "ARM_CLIENT_SECRET missing"
        else
          echo "ARM_CLIENT_SECRET exists"
        fi

        if [ -z "$ARM_SUBSCRIPTION_ID" ]; then
          echo "ARM_SUBSCRIPTION_ID missing"
        else
          echo "ARM_SUBSCRIPTION_ID exists"
        fi

        if [ -z "$ARM_TENANT_ID" ]; then
          echo "ARM_TENANT_ID missing"
        else
          echo "ARM_TENANT_ID exists"
        fi

    # -----------------------
    # Build Image
    # -----------------------
    - name: Build Image
      run: |
        packer build \
         -var "client_id=${{ secrets.ARM_CLIENT_ID }}" \
         -var "client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
          -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
         -var "tenant_id=${{ secrets.ARM_TENANT_ID }}" \
          ./packer/windows-iis.pkr.hcl

    # -----------------------
    # Install jq
    # -----------------------
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    # -----------------------
    # Extract Image ID
    # -----------------------
    - name: Extract Image ID
      run: |
        IMAGE_ID=$(jq -r '.builds[0].artifact_id' packer/packer-manifest.json)
        echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

    # -----------------------
    # Setup Terraform
    # -----------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # -----------------------
    # Terraform Init
    # -----------------------
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    # -----------------------
    # Terraform Apply
    # -----------------------
    - name: Terraform Apply
      working-directory: ./terraform
      run: |
        terraform apply -auto-approve \
          -var="image_id=$IMAGE_ID"